version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    command: ["/rails/bin/docker-entrypoint", "bundle", "exec", "rails", "server", "-b", "", "-p", "3000"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
